var a;
document.write("Value after variable declaration is " +a);
var a = 5;
document.write("<br>Initial Value: " +a);
a=++a;
document.write("<br>Value after increment is: " +a);
a=a+=7;
document.write("<br>Value after addition is: "+a);
a=--a;
document.write("<br>Value after decrement is: " +a);
a=a%3;
document.write("<br>The Remainder is: "+a);